-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:4695bbfee9d1ee1ee63fdf6b9b801252$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "cancel_button.png",
				spriteColorRect = { x = 4, y = 6, width = 123, height = 116 },
				textureRect = { x = 274, y = 358, width = 123, height = 116 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cancel_button_pressed.png",
				spriteColorRect = { x = 1, y = 2, width = 127, height = 124 },
				textureRect = { x = 145, y = 358, width = 127, height = 124 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "facebook_button.png",
				spriteColorRect = { x = 0, y = 2, width = 141, height = 139 },
				textureRect = { x = 2, y = 228, width = 141, height = 139 },
				spriteSourceSize = { width = 141, height = 141 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "post_button.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				textureRect = { x = 275, y = 228, width = 128, height = 128 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "post_button_selected.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				textureRect = { x = 145, y = 228, width = 128, height = 128 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "twitter_BG.png",
				spriteColorRect = { x = 0, y = 0, width = 468, height = 224 },
				textureRect = { x = 2, y = 2, width = 468, height = 224 },
				spriteSourceSize = { width = 470, height = 224 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "twitter_button.png",
				spriteColorRect = { x = 4, y = 6, width = 114, height = 113 },
				textureRect = { x = 2, y = 369, width = 114, height = 113 },
				spriteSourceSize = { width = 119, height = 119 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

